Add TeX installation instruction for Mac
`apt-get install` does not work, it should be `brew`, but then you get:

    brew install texlive
    Error: No available formula with the name "texlive" 
    Installing TeX from source is weird and gross, requires a lot of patches,
    and only builds 32-bit (and thus can't use Homebrew deps on Snow Leopard.)

    We recommend using a MacTeX distribution: https://www.tug.org/mactex/

Mactex takes 5.4GB on my computer :scream: will see if it's worth it.